---
AWSTemplateFormatVersion: 2010-09-09
Description: Send Messages Between Distributed Applications with Amazon Simple Queue Service (SQS)
Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "Orders"
      MessageRetentionPeriod: 86400 # 24 hours in seconds
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref Queue
      PolicyDocument:
        Statement:
          -
            Sid: __owner_statement
            Effect: "Allow"
            Principal:
              AWS:
                - !Ref "AWS::AccountId"
            Action:
              - "SQS:*"
            Resource: !Ref Queue

